name: motoshop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  line_icons: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/json/motos.json
    - assets/imagens/BMWF750.jpeg
    - assets/imagens/BMWF850GS.jpeg
    - assets/imagens/BWMS1000.jpeg
    - assets/imagens/HondaCB1000R.jpeg
    - assets/imagens/HondaCBR1000RRR.jpeg
    - assets/imagens/KawasakiVersys1000.jpeg
    - assets/imagens/Kawasakiz900.jpeg
    - assets/imagens/KawasakiZ1000.jpeg
    - assets/imagens/SuzukiGXSS1000.jpeg
    - assets/imagens/SuzukiVStrom1050.jpeg
    - assets/imagens/Tracer900.jpeg
    - assets/imagens/Triumph900.jpeg
    - assets/imagens/TriumphStreet.jpeg
    - assets/imagens/YamahaMT09.jpeg
