// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqaW_xQfAXhplfHEB0kFapoFTFM6wjQ10',
    appId: '1:610361540028:web:b4b6c400224a77990ebfb9',
    messagingSenderId: '610361540028',
    projectId: 'motoshop-3be5d',
    authDomain: 'motoshop-3be5d.firebaseapp.com',
    storageBucket: 'motoshop-3be5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAus2r1uR3RgR_OIs8_bq4V3WTMbkqslfo',
    appId: '1:610361540028:android:8e204f1bf394dfce0ebfb9',
    messagingSenderId: '610361540028',
    projectId: 'motoshop-3be5d',
    storageBucket: 'motoshop-3be5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ji3ZE22YLErfbarB-th3UPxEgY14cqU',
    appId: '1:610361540028:ios:80ba700bc26f14b70ebfb9',
    messagingSenderId: '610361540028',
    projectId: 'motoshop-3be5d',
    storageBucket: 'motoshop-3be5d.appspot.com',
    iosBundleId: 'com.example.motoshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ji3ZE22YLErfbarB-th3UPxEgY14cqU',
    appId: '1:610361540028:ios:80ba700bc26f14b70ebfb9',
    messagingSenderId: '610361540028',
    projectId: 'motoshop-3be5d',
    storageBucket: 'motoshop-3be5d.appspot.com',
    iosBundleId: 'com.example.motoshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqaW_xQfAXhplfHEB0kFapoFTFM6wjQ10',
    appId: '1:610361540028:web:c24c461fd3395a7a0ebfb9',
    messagingSenderId: '610361540028',
    projectId: 'motoshop-3be5d',
    authDomain: 'motoshop-3be5d.firebaseapp.com',
    storageBucket: 'motoshop-3be5d.appspot.com',
  );
}
