
FROM python:latest


WORKDIR /app


COPY . .


RUN pip install --upgrade pip && \
    pip install --no-cache-dir fastapi uvicorn mysql-connector-python


EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
